import { Product } from './types';
// @ts-ignore
import kitchenBanner from './assets/images/kitchen_banner_1780768180085.png';

export const CATEGORIES = [
  { id: 'sofa-covers', name: 'Sofa Covers', icon: 'Armchair', count: 6, desc: 'Premium velvet & stretch covers' },
  { id: 'table-cloths', name: 'Table Cloths & Decor', icon: 'Sparkles', count: 5, desc: 'Waterproof covers & decor' },
  { id: 'kitchen', name: 'Kitchen Accessories', icon: 'Utensils', count: 7, desc: 'Smart kitchen tools & racks' },
  { id: 'appliances', name: 'Home Appliances', icon: 'Tv', count: 8, desc: 'Reliable electric appliances' },
  { id: 'mobile-accessories', name: 'Mobile Accessories', icon: 'Smartphone', count: 9, desc: 'Cables, power banks & earbuds' },
  { id: 'gadgets', name: 'Useful Gadgets', icon: 'Zap', count: 8, desc: 'Innovative day-to-day devices' },
  { id: 'beauty', name: 'Beauty Essentials', icon: 'Gem', count: 3, desc: 'Premium self grooming & skin care' }
];

export const PAKISTAN_CITIES = [
  'Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Gujranwala', 
  'Peshawar', 'Multan', 'Hyderabad', 'Islamabad', 'Quetta', 
  'Sargodha', 'Sialkot', 'Bahawalpur', 'Sukkur', 'Jhang', 
  'Shekhupura', 'Mardan', 'Gujrat', 'Larkana', 'Kasur'
];

export const PRODUCTS: Product[] = [
  // --- SOFA COVERS ---
  {
    id: 'sofa-stretch',
    name: 'Premium Stretch Sofa Cover',
    price: 1499,
    originalPrice: 2200,
    description: 'Protect your couch with our premium, highly stretchable velvet sofa covers.',
    longDescription: 'Faizan Traders premium stretch sofa covers are designed with high-density spandex polyester blend fabric that fits snugly like a glove. These covers protect your precious furniture from pet scratches, stains, dust, and daily wear-and-tear while transforming old worn-out couches into beautiful centerpieces. Easily washable and fits most standard sofas.',
    image: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&q=80&w=600',
    images: [
      'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&q=80&w=600', 
      'https://images.unsplash.com/photo-1581539250439-c96689b516dd?auto=format&fit=crop&q=80&w=600',
      'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=600'
    ],
    rating: 4.8,
    reviewsCount: 124,
    category: 'sofa-covers',
    features: ['Machine washable', 'Stretches up to 30%', 'Anti-skid foam bars included', 'Pet & kid-friendly material'],
    variants: ['Ocean Blue', 'Charcoal Grey', 'Coffee Brown', 'Crimson Red', 'Beige Cream'],
    sizes: ['1 Seater', '2 Seater', '3 Seater', '4 Seater'],
    stock: 45,
    badge: 'Best Seller'
  },
  {
    id: 'sofa-elastic',
    name: 'Elastic Fitted Sofa Slipcovers',
    price: 1299,
    originalPrice: 1850,
    description: 'Easy-to-fit elasticated borders ensure the cover stays in place without shifting.',
    longDescription: 'Featuring durable 360-degree elastic bands, our fitted slipcovers snap instantly onto your single/double/triple cushion seats. Crafted with lightweight breathable micro-fiber textiles that donâ€™t sweat and feel exceptionally soft during warm Pakistani summers.',
    image: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&q=80&w=600',
    rating: 4.6,
    reviewsCount: 88,
    category: 'sofa-covers',
    features: ['360-degree elastic wrap', 'Breathable cool-tech fabric', 'Dust-mite resistant', 'Wrinkle-free design'],
    variants: ['Classic Black', 'Navy Blue', 'Forest Green', 'Teal'],
    sizes: ['1 Seater', '2 Seater', '3 Seater'],
    stock: 30,
    badge: 'Popular'
  },
  {
    id: 'sofa-printed',
    name: 'Modern Printed Sofa Cover Set',
    price: 1699,
    originalPrice: 2600,
    description: 'Vibrant geometric and botanical patterns to instantly elevate your drawing room look.',
    longDescription: 'Add artistic elegance to your lounge with our vibrant, high-definition printed cover sets. Using state-of-the-art reactive dye technology, the prints resist fading after multiple washes. The premium fabric feels buttery soft and brings immediate warmth to your home interior.',
    image: 'https://images.unsplash.com/photo-1581539250439-c96689b516dd?auto=format&fit=crop&q=80&w=600',
    rating: 4.7,
    reviewsCount: 41,
    category: 'sofa-covers',
    features: ['Non-fading reactive print', 'Pre-shrunk cotton-spandex blend', 'Includes matches cushion covers (2ct)', 'Sophisticated styling'],
    variants: ['Nordic Stripe', 'Floral Bloom', 'Golden Wave', 'Abstract Marble'],
    sizes: ['5 Seater Set (3+1+1)', '7 Seater Set (3+2+1+1)'],
    stock: 12,
    badge: 'Trending'
  },
  {
    id: 'sofa-lshape',
    name: 'Heavy Duty L-Shaped Sectional Cover',
    price: 3499,
    originalPrice: 4800,
    description: 'Specially structured cover set designed for modern corner and L-shaped sectionals.',
    longDescription: 'No more searching for separate corner pieces. Our heavy-duty L-shape cover comes as a set of 2 separate elastic covers that conform flawlessly around sharp corners. Made from reinforced triple-weave fabric for maximum longevity and resistance to heavy usage.',
    image: 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 56,
    category: 'sofa-covers',
    features: ['Heavyweight reinforced weave', 'Tailored for corner sectionals', 'Includes holding straps', 'Tear-resistant stitching'],
    variants: ['Stone Gray', 'Luxury White', 'Midnight Blue', 'Khaki'],
    sizes: ['Standard Medium', 'Extra Large'],
    stock: 18,
    badge: 'Premium'
  },
  {
    id: 'sofa-waterproof',
    name: '100% Waterproof Quilted Sofa Protector',
    price: 1999,
    originalPrice: 3000,
    description: 'Liquid-proof guard perfect for homes with toddlers, babies, and lively indoor pets.',
    longDescription: 'Spill a glass of juice or tea? Don\'t sweat it. Our quilted furniture protector uses a multi-layered barrier fabric with a waterproof TPU backing that stops liquids from reaching your precious sofa instantly. Simply wipe away messes with a clean cloth.',
    image: 'https://images.unsplash.com/photo-1512211546369-0477d5ffd2d2?auto=format&fit=crop&q=80&w=600',
    rating: 4.5,
    reviewsCount: 95,
    category: 'sofa-covers',
    features: ['100% Water & liquid resistant', 'Double quilted batting layer', 'Non-slip backing granules', 'Side storage pockets'],
    variants: ['Dual Grey-White', 'Reversible Brown-Khaki'],
    sizes: ['1 Seater', '2 Seater', '3 Seater'],
    stock: 25,
    badge: 'Kid-Safe'
  },
  {
    id: 'sofa-luxury',
    name: 'Luxury Royal Velvet Sofa Cover Set',
    price: 2499,
    originalPrice: 3800,
    description: 'Give your lounge a grand, palace-like atmosphere with ultra-soft royal velvet feel.',
    longDescription: 'Made of plush luxury Dutch velvet, this material offers unmatched shine, velvety thickness, and a rich finish that reflects light elegantly. Finished with clean laser-fringe borders, it is the ultimate upgrade for wedding setups or dynamic modern living rooms.',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=600',
    rating: 5.0,
    reviewsCount: 37,
    category: 'sofa-covers',
    features: ['High-pile shimmering velvet', 'Luxurious thick handfeel', 'Anti-slip lining', 'Elegant gift packaging'],
    variants: ['Emerald Green', 'Royal Crimson', 'Imperial Gold', 'Sapphire Blue'],
    sizes: ['5 Seater Set', '7 Seater Set'],
    stock: 8,
    badge: 'Luxury'
  },

  // --- TABLE CLOTHS & HOME DECOR ---
  {
    id: 'table-dining',
    name: 'Heavy Lace Dining Table Cover',
    price: 999,
    originalPrice: 1500,
    description: 'Elegant linen table cloth finished with exquisite floral border lace details.',
    longDescription: 'Make family dinners and guest parties special. Our lace dining table cloths combine sturdy flax-cotton centers with beautifully hand-refined borders. Spill-resistant and heat-defending to protect expensive wooden dining tabletops.',
    image: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?auto=format&fit=crop&q=80&w=600',
    rating: 4.7,
    reviewsCount: 49,
    category: 'table-cloths',
    features: ['Heat-defending barriers', 'Exquisite cotton-lace fringes', 'Anti-stain surface properties', 'Available in multi-seater sizes'],
    variants: ['Ivory Lace', 'Rustic Flax', 'Peony Pink'],
    sizes: ['4 Chair Table', '6 Chair Table', '8 Chair Table'],
    stock: 35
  },
  {
    id: 'table-printed',
    name: 'Boho Printed Canvas Table Cloth',
    price: 799,
    originalPrice: 1200,
    description: 'Minimalist geometrical printed patterns for a modern, artistic kitchen feel.',
    longDescription: 'Add effortless Nordic vibes to your dining area. This high-grade cotton canvas cloth features hand-blocked geometric tiles and rich textures that resist fading. Heavily weighted to hang nicely at the corners.',
    image: 'https://images.unsplash.com/photo-1503418895522-46f9804cda40?auto=format&fit=crop&q=80&w=600',
    rating: 4.5,
    reviewsCount: 32,
    category: 'table-cloths',
    features: ['Heavy canvas fabric', 'Bohemian tassels decoration', 'Premium reactive ink block'],
    variants: ['Grey Chevron', 'Yellow Arrow', 'Blue Mosaic'],
    sizes: ['6 Chair Table', '8 Chair Table'],
    stock: 40
  },
  {
    id: 'table-waterproof',
    name: 'Vinyl Waterproof Wipeable Table Cover',
    price: 1199,
    originalPrice: 1800,
    description: 'Thick crystal clear PVC / vinyl printed cover to guard the table from spills.',
    longDescription: 'Tired of scrubbing food grease and curry stains? Simply spray and wipe! This heavy-weight vinyl cover is transparent with gold-foil floral patterns. Highly heat-resistant (up to 80Â°C) - perfect for piping hot serving dishes.',
    image: 'https://images.unsplash.com/photo-1544982503-9f984c14501a?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 74,
    category: 'table-cloths',
    features: ['Oil & grease repellent', 'Heat insulation core', 'Non-discoloring clear print', 'Heavy weight drop'],
    sizes: ['6 Chair Table', '8 Chair Table'],
    stock: 22,
    badge: 'Easy Clean'
  },
  {
    id: 'table-center',
    name: 'Embroidered Center Table Runner',
    price: 599,
    originalPrice: 950,
    description: 'Delicate table runner designed with traditional thread embroidery styles.',
    longDescription: 'Bring classic Pakistani hospitality to your coffee table. Handcrafted with fine floral embroidery on sheer organza backed by soft satin, this center runner acts as a beautiful focal point for serving dry fruits or tea setup.',
    image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&q=80&w=600',
    rating: 4.6,
    reviewsCount: 19,
    category: 'table-cloths',
    features: ['Traditional thread-work styling', 'Dual satin-organza layers', 'Perfect for drawing room shelves'],
    variants: ['Golden Jasmine', 'Silver Lilac', 'Rose Copper'],
    stock: 50
  },
  {
    id: 'decor-accessories',
    name: 'Geometric Glass Hanging Terrarium Vases',
    price: 1299,
    originalPrice: 1950,
    description: 'Pair of brass metal geometric frames holding stylish glass floating flower tubes.',
    longDescription: 'Brighten dark corners or plain walls with these wall-mountable metallic flower vessels. The stylish grid brass frame holds high-transparency glass tubes ideal for propogating plants, fresh jasmines, or stylish artificial buds.',
    image: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=600',
    rating: 4.4,
    reviewsCount: 23,
    category: 'table-cloths',
    features: ['Rust-resistant gold coating', 'Toughened laboratory glass', 'Easy mounting loop hooks', 'Matches modern interior designs'],
    stock: 15,
    badge: 'Special Gift'
  },

  // --- KITCHEN ACCESSORIES ---
  {
    id: 'kitchen-containers',
    name: 'Air-Tight Seasoning & Grain Containers Set',
    price: 699,
    originalPrice: 1100,
    description: 'Set of 6 high-grade leakproof plastic dispensers to keep staples completely fresh.',
    longDescription: 'Keep moisture and creepy-crawlies far away from your spices, rice, and sugar. Crafted with Food-Safe BPA-free clear acrylic plastics and dual-lock clip lids that prevent air flow. Space-saving stackable designs.',
    image: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?auto=format&fit=crop&q=80&w=600',
    rating: 4.6,
    reviewsCount: 112,
    category: 'kitchen',
    features: ['100% Air-tight silicone clips', 'BPA-free acrylic body', 'Stackable space-efficient molds', 'Include labeling markers'],
    stock: 60,
    badge: 'Super Deal'
  },
  {
    id: 'kitchen-spicerack',
    name: '2-Tier Rotating Spices Rack Organizer',
    price: 1299,
    originalPrice: 1900,
    description: '360-degree turntable lazy susan to instantly discover spices on nested shelves.',
    longDescription: 'Never make a mess looking for chili powder during high-pressure cooking! Our revolving turntable spins effortlessly with silent bearings, keeping all jars accessible in dark pantry drawers or right beside the cooker hob.',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 65,
    category: 'kitchen',
    features: ['Spins 360 smoothly', 'Anti-slip rubberized shelf surface', 'Double drawer heights', 'Anti-rust stainless handles'],
    stock: 28
  },
  {
    id: 'kitchen-organizer',
    name: 'Under-Sink Expandable Utility Rack',
    price: 1499,
    originalPrice: 2200,
    description: 'Adjustable length kitchen shelf structure to custom fit around cabinet plumbing.',
    longDescription: 'Tackle the absolute mess under your kitchen sink. Our adjustable organizer stretches horizontally and vertical shelf levels can be moved dynamically around water pipes, making full room for dishwashes, sponges, and heavy utensils.',
    image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&q=80&w=600',
    rating: 4.7,
    reviewsCount: 42,
    category: 'kitchen',
    features: ['Expandable length (50-80cm)', 'Heavyweight metal support beams', 'Washable flat panel trays', 'No drill setup tool'],
    stock: 19,
    badge: 'Must Have'
  },
  {
    id: 'kitchen-cutter',
    name: 'Multi-blade Fast Vegetable Chopper Set',
    price: 899,
    originalPrice: 1500,
    description: 'Saves 70% prep duration! Includes 8 easy interchangeable stainless blades.',
    longDescription: 'Dice onions, grate carrots, crinkle slice potatoes, and wash salad with one master utensil. Simply click the custom blades and press down the top lever. The integrated grid tray catches all chopped pieces instantly with no odor or tears.',
    image: 'https://images.unsplash.com/photo-1506368249639-73a05d6f6488?auto=format&fit=crop&q=80&w=600',
    rating: 4.5,
    reviewsCount: 143,
    category: 'kitchen',
    features: ['Interchangeable stainless steel blades', 'Large integrated colander basket', 'Non-slip grip feet', 'Easy cleaner claw accessory'],
    stock: 50,
    badge: 'Time Saver'
  },
  {
    id: 'kitchen-dryingrack',
    name: 'Over-The-Sink Roll-Up Dish Drying Rack',
    price: 1999,
    originalPrice: 2800,
    description: 'Foldable steel bar mat to dry washed cutlery directly over your steel sink basin.',
    longDescription: 'Drip-dry pans, plates, and fresh fruits directly into the drain pipeline with our portable rolling dryer matrix. Silicone-covered durable stainless steel rods hold up to 15kg weight without bending. Rolls away instantly when not in use.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 38,
    category: 'kitchen',
    features: ['Food-grade silicone wrap', 'Extremely heavy-load bearing', 'Rustproofing guaranteed', 'Dishwasher secure design'],
    stock: 14
  },
  {
    id: 'kitchen-measuring',
    name: 'Digital High Precision Kitchen Spoon Scale',
    price: 499,
    originalPrice: 850,
    description: 'Weigh milk powder, salt, baking flour, and butter from 0.1g to 500g instantly.',
    longDescription: 'Perfect resource for strict recipe measurements and health tracking. Scoop ingredients directly and read the weights on an bright LCD readout. Auto-turns off after idling.',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=600',
    rating: 4.4,
    reviewsCount: 89,
    category: 'kitchen',
    features: ['Readings range from 0.1g to 500g', 'Grams/Ounces conversion support', 'Hold and Tare logic buttons', 'Batteries included'],
    stock: 75
  },
  {
    id: 'kitchen-cleaning',
    name: 'Long Handle Liquid Dispenser Pan Brush',
    price: 399,
    originalPrice: 600,
    description: 'Press the silicone button to feed dishwash liquid directly to continuous heavy scrubbing.',
    longDescription: 'Stop dunking your fingers in grease! Our utility soap dispenser brush lets you scrub baking pans with tough wire and soft sponge heads while feeding dishwashing liquid gently with your thumb on the top button.',
    image: 'https://images.unsplash.com/photo-1610557892470-76d747e9253f?auto=format&fit=crop&q=80&w=600',
    rating: 4.3,
    reviewsCount: 156,
    category: 'kitchen',
    features: ['Includes sponge and nylon scrub brush heads', 'Zero-leak soap storage rod', 'Saves soap usage by 50%', 'Hanging tail loop'],
    stock: 120
  },

  // --- HOME APPLIANCES ---
  {
    id: 'appliance-kettle',
    name: 'Rapid Boil Cordless Electric Kettle',
    price: 2199,
    originalPrice: 3200,
    description: '1.8L food-safe steel kettle boasting instant 1500W heating coils.',
    longDescription: 'Brew morning tea or chai instantly with our heavy-duty kettle. Constructed with triple-layer steel walls and a heat-insulated stay-cool touch exterior handle. Auto-shutoff immediately kicks in as boiling limits are reached.',
    image: 'https://images.unsplash.com/photo-1594385208974-2e75f9d8ab48?auto=format&fit=crop&q=80&w=600',
    rating: 4.7,
    reviewsCount: 104,
    category: 'appliances',
    features: ['Double insulated touch protection', 'Heat auto shutoff', 'Food quality 304 Stainless Steel', '360-degree rotating base'],
    stock: 32,
    badge: 'Winter Special'
  },
  {
    id: 'appliance-blender',
    name: 'USB Rechargeable Wireless Mini Juicer',
    price: 1799,
    originalPrice: 2800,
    description: '6-Blades ultra sharp dynamic portal motor in a smart sports bottle design.',
    longDescription: 'Sip fresh smoothies and pure fruit protein shakes anywhere! Our rechargeable shaker packs an insanely fast 22,000 RPM motorized turbine base. USB charges in 2 hours to service up to 15 individual cups on a single cycle.',
    image: 'https://images.unsplash.com/photo-1578643463396-0997cb5328c1?auto=format&fit=crop&q=80&w=600',
    rating: 4.6,
    reviewsCount: 178,
    category: 'appliances',
    features: ['Unmatched 6 spiral stainless cutters', 'Rechargeable through Type-C port', 'Auto cleaning shake run', 'BPA-free medical grader PCTG'],
    stock: 45,
    badge: 'Best Seller'
  },
  {
    id: 'appliance-juicer',
    name: 'Heavy-Duty 2-in-1 Juicer & Grinder',
    price: 3499,
    originalPrice: 5000,
    description: 'Extract raw citrus juice and pulverize coffee spices with double jar heads.',
    longDescription: 'Perfect commercial helper for Pakistani homes. Grinds dry spices like cumin, ginger, and turmeric to super-fine consistency while the separate high-volume blender jar handles heavy mango milkshakes or purÃ©es effortlessly.',
    image: 'https://images.unsplash.com/photo-1579613832125-5d34a13feb2a?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 53,
    category: 'appliances',
    features: ['Heavy Copper 450W quiet motor', 'Dual rotation rates', 'High resistance glass jars', 'Suction lock feet'],
    stock: 15
  },
  {
    id: 'appliance-chopper',
    name: 'Electric Quick Meat & Vegetable Chopper',
    price: 1999,
    originalPrice: 3000,
    description: '2-Liter steel container that chops korma masala and mince beef/chicken in seconds.',
    longDescription: 'Mince meat for quick home seekh-kebabs instantly. Features four modular double-deck steel blades that cut evenly throughout the 2-liter heavy duty bowl.',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 91,
    category: 'appliances',
    features: ['Durable steel bowl (no breaks)', 'Dual speeds logic handle', 'Safety auto-lock engine switch', 'Anti-heat wrap system'],
    stock: 24,
    badge: 'Masala Expert'
  },
  {
    id: 'appliance-iron',
    name: 'Fast-Heat Steam Spray Flat Iron',
    price: 2899,
    originalPrice: 4200,
    description: 'Teflon coated scratch-free baseplate with micro steam jet spray nozzles.',
    longDescription: 'Remove hard wrinkles from cotton kurtas on our specialized steam iron. Glides effortlessly on delicate silks or thick shalwar-kameez linen fabrics alike. Powerful steam bursts sanitize materials on the fly.',
    image: 'https://images.unsplash.com/photo-1510551310160-589462daf284?auto=format&fit=crop&q=80&w=600',
    rating: 4.5,
    reviewsCount: 47,
    category: 'appliances',
    features: ['Non-stick luxury Teflon base', 'Active anti-drip valve structures', '300ml dynamic liquid drawer', 'Precise thermal scroll wheel'],
    stock: 16
  },
  {
    id: 'appliance-fan',
    name: 'Rechargeable Desk Fan with Ring LED Light',
    price: 4499,
    originalPrice: 6500,
    description: 'Backup air wind for heavy load shedding! Features 4000mAh long battery reserve.',
    longDescription: 'Survive uncomfortable power shedding! This dynamic desk fan has robust adjustable fan speeds, wide 120-degree automatic rotations, and an integrated bright nightlight lamp base to study or work in breeze under blackout periods.',
    image: 'https://images.unsplash.com/photo-1618944913480-b67ee16d7b77?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 112,
    category: 'appliances',
    features: ['Rechargeable 4000mAh battery block', 'Runs up to 8 continuous hours', 'Integrated bright selfie/reading light', 'Super whisper motor sound'],
    stock: 20,
    badge: 'Summer Essential'
  },
  {
    id: 'appliance-emergencylight',
    name: 'Heavy Duty 60 LED Rechargeable Lantern',
    price: 1299,
    originalPrice: 2000,
    description: 'Bright backup spotlight with easy carry handle and wall mounting options.',
    longDescription: 'Never stay details in darkness during surprise load sheddings. This heavy-duty backing light contains 60 separate ultra-bright SMD LEDs providing cool daylight flood illumination across standard living rooms with multiple output controls.',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&q=80&w=600',
    rating: 4.7,
    reviewsCount: 82,
    category: 'appliances',
    features: ['60 luminous surface SMDs', 'Overcharge cut protection', 'Integrated hanging handle', 'USB battery bank exit port'],
    stock: 35
  },
  {
    id: 'appliance-ledlamp',
    name: 'Smart Golden Ring Desk LED Lamp',
    price: 899,
    originalPrice: 1450,
    description: 'Touch control night stand light with triple tone dimmable color filters.',
    longDescription: 'An elegant addition to bedside tables or kids desks. Gentle on the eyes, this smart LED ring adjusts color warmths (warm yellow, natural sunset, cold study white) with the touch of a button.',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&q=80&w=600',
    rating: 4.6,
    reviewsCount: 39,
    category: 'appliances',
    features: ['Touch panel interaction', 'Eye comfort zero-flicker panels', '360 degree pose flexibility', 'Brings luxury ambiance'],
    stock: 40
  },

  // --- MOBILE ACCESSORIES ---
  {
    id: 'mobile-charger',
    name: 'Fast Charge Quick Adapter 20W',
    price: 599,
    originalPrice: 990,
    description: 'Safe dual-port fast charger with intelligent smart matching current chips.',
    longDescription: 'Safely juice up iPhones and Android models at hyper speed. The integrated circuit monitors device vitals to protect against voltage jumps, spikes, heating, or power surges.',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=600',
    rating: 4.7,
    reviewsCount: 167,
    category: 'mobile-accessories',
    features: ['Saves 50% charging duration', 'Double Type-C / USB exit plugs', 'Smart power regulation', 'Universal country pin fits'],
    stock: 110,
    badge: '100% Original'
  },
  {
    id: 'mobile-adapter',
    name: 'Super Fast Turbo Charger Adapter 45W',
    price: 999,
    originalPrice: 1600,
    description: 'Premium Gallium Nitride (GaN) high wattage charger to boost laptops and smartphones.',
    longDescription: 'Small size, massive wattage. Using thermal-efficient GaN tech, this micro adapter scales charging output to quickly deliver secure currents matching iPads, laptops, or flagship smartphones.',
    image: 'https://images.unsplash.com/photo-1622445262468-2481855797e9?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 94,
    category: 'mobile-accessories',
    features: ['Gallium Nitride cooler components', 'Uncompromising 45 Watt output', 'Foldable plug architecture', 'Supports Samsung Super Fast Charging 2.0'],
    stock: 65,
    badge: 'Premium'
  },
  {
    id: 'mobile-cable',
    name: 'Tough Nylon Braided 3-in-1 Charging Cord',
    price: 349,
    originalPrice: 550,
    description: 'One cord connects Type-C, Lightning, and Micro USB devices at once.',
    longDescription: 'Avoid carry clusters of charging lines. Our heavy military-braid nylon line has triple standard outlets to fuel all personal electronics from a single connector base.',
    image: 'https://images.unsplash.com/photo-1541667593105-0507ef1b29a2?auto=format&fit=crop&q=80&w=600',
    rating: 4.5,
    reviewsCount: 215,
    category: 'mobile-accessories',
    features: ['Triple heads (Type C, Micro, Lightning)', 'Tough braided nylon exterior', 'Generous 1.2-meter reach', 'Anti-snag rubber joints'],
    stock: 150,
    badge: 'Hot Seller'
  },
  {
    id: 'mobile-powerbank',
    name: '20,000mAh Power Bank with LCD Screen',
    price: 2499,
    originalPrice: 3800,
    description: 'Bulk smart power backup with digital fuel percentage display screen.',
    longDescription: 'Charge flagship modern smartphones 4 to 5 times effortlessly during travel or remote sites. Sleek portable profile with triple high-speed charging outputs.',
    image: 'https://images.unsplash.com/photo-1609592806509-f6ba6df2bc26?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 103,
    category: 'mobile-accessories',
    features: ['Huge 20,000mAh reserve capacity', 'Fast charging 22.5W output support', 'Real-time remaining battery % display', 'Double LED torch light in front'],
    stock: 45,
    badge: 'Travel Gear'
  },
  {
    id: 'mobile-holder',
    name: 'Adjustable Metal Desktop Smartphone Stand',
    price: 499,
    originalPrice: 800,
    description: 'Foldable aluminum alloy stand with protective anti-skid silicone pads.',
    longDescription: 'Browse recipes, take Zoom meetings, or stream dramas comfortably with hands-free angles. Full height adjustability with absolute metal stability.',
    image: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=600',
    rating: 4.6,
    reviewsCount: 88,
    category: 'mobile-accessories',
    features: ['Sleek solid Aluminum alloy build', 'Customizable tilts & heights', 'Anti-slip bottom rubber paddings', 'Pocket-sized fold layout'],
    stock: 80
  },
  {
    id: 'mobile-earbuds',
    name: 'Premium TWS Wireless Earbuds Gaming Edition',
    price: 1999,
    originalPrice: 3200,
    description: 'Deep high-impact acoustics boasting low-delay gaming latency speeds.',
    longDescription: 'Experience crisp vocal details and deep punchy bass. Auto pair immediately, with full touch gesture support and an intelligent charging pod matching 30+ playback hours.',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&q=80&w=600',
    rating: 4.7,
    reviewsCount: 145,
    category: 'mobile-accessories',
    features: ['Low 40ms audio response latency', 'Active IPX5 moisture sealants', 'Continuous playback 32 hours back up', 'Hi-Fi voice calls microphones'],
    stock: 55,
    badge: 'Top Choice'
  },
  {
    id: 'mobile-speakers',
    name: 'Portable Waterproof Bluetooth Speaker Out-5W',
    price: 1499,
    originalPrice: 2400,
    description: 'Compact wireless speaker delivering rich sound with dynamic pulsing lights.',
    longDescription: 'Blast room-filling sound on family picnics or in drawing rooms. Bluetooth 5.1 ensures stable pairing up to 15 meters away with high-definition wireless signals.',
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&q=80&w=600',
    rating: 4.5,
    reviewsCount: 67,
    category: 'mobile-accessories',
    features: ['Durable weave wrap design', 'Rich passive radiator bass lines', 'Dazzling dual LED rings', 'Supports TF Cards and Aux line'],
    stock: 38
  },
  {
    id: 'mobile-cases',
    name: 'Luxury Frosted Matt Armor Phone Case',
    price: 450,
    originalPrice: 700,
    description: 'Impact absorbing bumper shell finished with customized frosted textures.',
    longDescription: 'High quality defense for iPhone, Samsung, and Infinix models. Soft TPU rims safeguard screen and camera corners from hard bumps.',
    image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&q=80&w=600',
    rating: 4.4,
    reviewsCount: 31,
    category: 'mobile-accessories',
    features: ['Frosted fingerprint shield', 'Independent click-feeling metal triggers', 'Shockproof safety drops', 'Minimalist build'],
    variants: ['Ocean Blue', 'Military Black', 'Olive Green'],
    stock: 90
  },
  {
    id: 'mobile-screen',
    name: '9H Hardness Shatterproof Tempered Glass',
    price: 250,
    originalPrice: 400,
    description: 'Oleophobic screen guard featuring seamless bubble-free install frames.',
    longDescription: 'Avoid expensive screen repairs! Our tempered glass boasts ultra-clear 9H density shield keeping keys or coins from scratching delicate glass surfaces.',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 405,
    category: 'mobile-accessories',
    features: ['Ultra-density 9H armor resistance', 'Highly hydrophobic coating repels fingerprints', 'Seamless screen touch responsiveness'],
    stock: 300,
    badge: 'Saver Pack'
  },

  // --- USEFUL GADGETS ---
  {
    id: 'gadget-rechargeable',
    name: 'Double-Tube Wardrobe Rechargeable Light',
    price: 999,
    originalPrice: 1500,
    description: 'Multi-strength emergency strip with high-strength magnetic bracket clips.',
    longDescription: 'Easily light up closets, dark kitchen backsplashes, or shoe racks. USB charging avoids wiring issues and holds up to 10 hours continuous daylight illumination.',
    image: 'https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 92,
    category: 'gadgets',
    features: ['Built-in high performance lithium block', 'Dynamic dual brightness filters', 'Sticks instantly to metallic sheets', 'Includes micro-USB chargers'],
    stock: 45,
    badge: 'Gadget Pick'
  },
  {
    id: 'gadget-motion',
    name: 'Wireless Motion Sensor Night Light',
    price: 699,
    originalPrice: 1100,
    description: 'Turns on automatically when human steps are noticed within a 10ft corridor scope.',
    longDescription: 'Protect kids and elders from stumbling at night. Our warm LED spot light triggers immediately when detecting footprints and auto-shuts within 25 seconds of zero motion.',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&q=80&w=600',
    rating: 4.7,
    reviewsCount: 154,
    category: 'gadgets',
    features: ['Sensitive infra PIR sensor', 'Sticks via double-face iron tapes', 'Soft glowing eye-safe warm white light', 'Battery operated (3 AAA)'],
    stock: 80,
    badge: 'Home Safety'
  },
  {
    id: 'gadget-vacuum',
    name: 'Portable Mini Rechargeable Car Vacuum Cleaner',
    price: 1899,
    originalPrice: 2800,
    description: 'Cordless dust buster with strong 6000PA motor for home & auto interior detailing.',
    longDescription: 'Quickly clean biscuits crumbs, dust webs, or pet hairs in between seat cracks. Cordless USB operation lets you detailing difficult ceiling lines comfortably.',
    image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&q=80&w=600',
    rating: 4.6,
    reviewsCount: 81,
    category: 'gadgets',
    features: ['Strong double cyclonic suction motor', 'Washable HEPA filter matrix', 'Narrow crevice brush heads included', 'Charges on car adaptors'],
    stock: 30,
    badge: 'Car Lover'
  },
  {
    id: 'gadget-portfan',
    name: 'Neck Hanging Hands-Free USB Portable Fan',
    price: 1299,
    originalPrice: 2000,
    description: 'Adjustable dual turbine head fan worn comfortably on the neck during cookings or travels.',
    longDescription: 'Keeps face dry and breezy on hot Pakistani bus travel or kitchen cookings. Triple speed variations deliver intense cooling without dangerous spinning fans.',
    image: 'https://images.unsplash.com/photo-1618944913480-b67ee16d7b77?auto=format&fit=crop&q=80&w=600',
    rating: 4.5,
    reviewsCount: 97,
    category: 'gadgets',
    features: ['Zero-hair tangle turbine grids', 'Double 360 flex wind directions', 'Runs quiet while sleeping', 'Ultra-lightweight skin safe build'],
    stock: 50
  },
  {
    id: 'gadget-car',
    name: 'Gravity Automatic Smartphone Air-Vent Car Holder',
    price: 1199,
    originalPrice: 1850,
    description: 'Slip in smartphone and watch gravity triggers auto-clamping metal brackets.',
    longDescription: 'Secure phone during jerky car rides! Auto clamps lock handsets firmly from three sides on dynamic gravity motions. High grade alloy avoids squeaks.',
    image: 'https://images.unsplash.com/photo-1485291571150-772bcfc10da5?auto=format&fit=crop&q=80&w=600',
    rating: 4.6,
    reviewsCount: 42,
    category: 'gadgets',
    features: ['Gravity auto-clamping mechanism', 'Vent guard protection silicone cushions', 'Supports 360 map rotations', 'Compatible up to 6.7 inch sizes-models'],
    stock: 45
  },
  {
    id: 'gadget-smartorg',
    name: 'Multi-Device Felt Bedside Hanging Caddy',
    price: 1499,
    originalPrice: 2200,
    description: 'Double layer felt bag hangs beside sofa arm or bed board to hold tablets, books, remotes.',
    longDescription: 'Keep everything organized near your rest sites. Constructed inside tough double strength thick materials keeping water glasses, phones, and glasses closely within stretch arms.',
    image: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&q=80&w=600',
    rating: 4.5,
    reviewsCount: 22,
    category: 'gadgets',
    features: ['Double-layer thick durable felt', 'Deep side storage pockets', 'Slips perfectly under mattress or sofa cushion', 'Holds laptops, tablets, and remotes easily'],
    stock: 34
  },
  {
    id: 'gadget-multitool',
    name: '18-in-1 Compact Snowflake Stainless Multi-Tool',
    price: 799,
    originalPrice: 1300,
    description: 'Pocket key ring with multiple open sockets, flat cutters, and screw driver tips.',
    longDescription: 'The ultimate tool for simple mechanical tightenings on home furniture or car engines. High grade stainless steel ensures zero bends.',
    image: 'https://images.unsplash.com/photo-1530124566582-ab059dd4c0f8?auto=format&fit=crop&q=80&w=600',
    rating: 4.7,
    reviewsCount: 57,
    category: 'gadgets',
    features: ['Heavy rust-proof premium chrome plating', '18 tool operations, incredibly compact', 'Fitted key loop lock'],
    stock: 120
  },
  {
    id: 'gadget-travel',
    name: 'Universal Portable Digital Hanging Luggage Scale',
    price: 1299,
    originalPrice: 2000,
    description: 'Avoid expensive airport fees! Measures weight up to 50kg with sharp blue screens.',
    longDescription: 'Simply hook luggage straps, suspend, and read weight indices instantly. Auto locked reading lets you easily scale baggages.',
    image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 68,
    category: 'gadgets',
    features: ['Lifting heavy strap holding hooks', 'Maximum weight load 50kg / 110lb', 'Auto-locks index indicators', 'Tare values clear button'],
    stock: 35,
    badge: 'Must Have'
  },
  {
    id: 'beauty-epilator',
    name: 'Rechargeable 5-in-1 Face Epilator & Massager',
    price: 1899,
    originalPrice: 2999,
    description: 'Cordless 5-in-1 facial beauty tool for precision epilation, cleansing, and massage.',
    longDescription: 'Pamper your skin at home! This 5-in-1 versatile device operates wirelessly, featuring quick-swap heads including an epilator, facial cleaning brush, massage roller, under-arm shaver, and callous remover. Ergonomic design with gentle touch on sensitive skin.',
    image: 'https://images.unsplash.com/photo-1616683693504-3ea7e9ad6fec?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 42,
    category: 'beauty',
    features: ['5 interchangeable premium heads', 'Gentle wet and dry micro-cleansing', 'USB fast charging backup', 'Soft travel pouch included'],
    stock: 45,
    badge: 'Trending'
  },
  {
    id: 'beauty-roller',
    name: 'Premium Rose Quartz Gua Sha & Facial Roller Set',
    price: 999,
    originalPrice: 1800,
    description: 'Natural healing pink gemstone double-roller paired with premium curved gua-sha.',
    longDescription: 'Relieve stress and contour facial lines smoothly. Real rose quartz stones offer cool soothing contact, helping activate beauty creams deeper, de-puffing morning skin lines, and restoring natural bright glow.',
    image: 'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 31,
    category: 'beauty',
    features: ['100% natural rose quartz stones', 'Noise-free silicone silent sleeves', 'Dual-ended sizing rollers', 'Elegantly gift-boxed packaging'],
    stock: 80
  },
  {
    id: 'beauty-straightener',
    name: 'Professional Ceramic Ionic Hair Straightener Brush',
    price: 2499,
    originalPrice: 3999,
    description: 'Instant anti-frizz heating comb for silky straight salon results in 5 minutes.',
    longDescription: 'Get perfectly straight hair without heat damage. Combining advanced ionic generator tech and 3D ceramic bristles to glide through tangles, detangling and smoothening coarse hair securely. Safe anti-scald frame ensures skin contact protection.',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13edd793be?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 54,
    category: 'beauty',
    features: ['30-second rapid PTC heat-up', 'Anion generators reduce fizz completely', 'Anti-scald shield teeth tip', 'Auto-shutdown countdown protection'],
    stock: 28,
    badge: 'Popular'
  }
];

export const REVIEWS = [
  { id: 'rev-1', writer: 'Zainab Bibi', rating: 5, date: 'May 24, 2026', text: 'Excellent quality sofa covers! They fit my 3-seater couch absolutely perfectly. The navy blue color looks very royal.' },
  { id: 'rev-2', writer: 'Muhammad Hamza', rating: 5, date: 'June 01, 2026', text: 'Ordered the kitchen organizers and mini blender. Very useful and reasonably priced. Will buy again from Faizan Traders.' },
  { id: 'rev-3', writer: 'Ayesha Khan', rating: 5, date: 'May 18, 2026', text: 'Highly recommended for home essentials and daily gadgets. Extremely rapid delivery to Lahore! Keep it up!' },
  { id: 'rev-4', writer: 'Bilal Ahmed', rating: 4, date: 'April 29, 2026', text: 'Fast charging adapter works great. The 3-in-1 cable is robust. Customer support on WhatsApp was extremely friendly.' },
  { id: 'rev-5', writer: 'Sana Fatima', rating: 5, date: 'June 03, 2026', text: 'Waterproof dining table cover is highly recommended. It saved my wooden table from several tea spills already.' }
];

export const BANNER_SLIDES = [
  {
    id: 'slide-kitchen-gadgets',
    title: 'Must-Have Gadgets',
    subtitle: 'For Every Kitchen & Daily Use',
    priceText: 'Premium Quality • Smart Cooking',
    badge: 'Trending Now 🔥',
    tagline: 'Powerful mini gadgets perfect for quick meals, juices, spices grinding and everyday home utility.',
    image: kitchenBanner,
    linkCategory: 'kitchen',
    bgColor: 'from-zinc-950 via-slate-900 to-zinc-950'
  },
  {
    id: 'slide-1',
    title: 'Transform Your Drawing Room',
    subtitle: 'Premium Stretch Sofa Covers',
    priceText: 'From Rs. 1,299 Only',
    badge: 'Flat 30% Off',
    tagline: 'Scratch-proof, dust-preventing elasticated stretch fits available in 15+ rich royal colors.',
    image: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&q=80&w=700',
    linkCategory: 'sofa-covers',
    bgColor: 'from-zinc-900 to-stone-900'
  },
  {
    id: 'slide-2',
    title: 'Smart Kitchen Upgrades',
    subtitle: 'Innovative Cooking Accessories',
    priceText: 'Starting Rs. 399',
    badge: 'Fast Seller',
    tagline: 'Make vegetable chopping, spice storage, and dish drying quick, neat, and highly organized.',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=700',
    linkCategory: 'kitchen',
    bgColor: 'from-slate-900 to-zinc-900'
  },
  {
    id: 'slide-3',
    title: 'Live Comfortably, Save Money',
    subtitle: 'Everyday Gadgets & Appliances',
    priceText: 'Nationwide Cash On Delivery',
    badge: 'Hot Deals',
    tagline: 'Reliable rechargeable study lights, fans, mini blender mixers, and mobile charge items in Pakistan.',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=700',
    linkCategory: 'gadgets',
    bgColor: 'from-neutral-950 to-stone-950'
  }
];
