import { Product, Review, BannerSlide } from './types';

export const CATEGORIES = [
  { id: 'all', name: 'All Products', icon: 'ShoppingBag', count: 19, desc: 'Explore all premium kids clothing' },
  { id: 'new-arrivals', name: 'New Arrivals', icon: 'Sparkles', count: 4, desc: 'Fresh collection for your little ones' },
  { id: 'best-sellers', name: 'Best Sellers', icon: 'Award', count: 4, desc: 'Most loved styles & designs' },
  { id: 'shorts-pants', name: 'Shorts & Pants', icon: 'Scissors', count: 4, desc: 'Comfortable cotton shorts & denim' },
  { id: 'nightsuits', name: 'Nightsuits', icon: 'Moon', count: 4, desc: 'Soft & cozy sleepwear nightsuits' },
  { id: 'essentials', name: 'Essentials', icon: 'ShoppingBag', count: 4, desc: 'Baby bags, carry nest & suites' }
];

export const COLLECTIONS = [
  { id: 'trending-gadgets', name: 'Trending Gadgets', image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=300' },
  { id: 'trending-fashion', name: 'Trending Fashion', image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=300' },
  { id: 'national-event', name: 'National & Event Wear', image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=300' },
  { id: 'ramadan-eid', name: 'Ramadan & Eid', image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&q=80&w=300' },
  { id: 'seasonal-collections', name: 'Seasonal Collections', image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&q=80&w=300' },
];

export const PAKISTAN_CITIES = [
  'Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Gujranwala', 
  'Peshawar', 'Multan', 'Hyderabad', 'Islamabad', 'Quetta', 
  'Sargodha', 'Sialkot', 'Bahawalpur', 'Sukkur', 'Jhang', 
  'Shekhupura', 'Mardan', 'Gujrat', 'Larkana', 'Kasur'
];

export const PRODUCTS: Product[] = [
  // --- BEST SELLERS ---
  {
    id: 'girls-white-embroidered',
    name: 'Girls White Embroidered Suit',
    price: 2274,
    originalPrice: 3249,
    description: 'Premium quality soft cotton fabric shirt with decorative embroidery paired with stylish sky blue shorts.',
    longDescription: 'This Girls White Embroidered Suit is crafted from high-grade cotton, ensuring ultimate softness and breathability on sensitive skin. Features beautiful artisanal embroidery details on the front, button-down front opening, and puff sleeves. Paired with coordinating light blue denim shorts with a decorative front bow. Durable stitching, non-fading dyes, and machine washable.',
    image: 'https://images.unsplash.com/photo-1515488042361-404e9250afef?auto=format&fit=crop&q=80&w=600',
    images: [
      'https://images.unsplash.com/photo-1515488042361-404e9250afef?auto=format&fit=crop&q=80&w=600',
      'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&q=80&w=600'
    ],
    rating: 4.9,
    reviewsCount: 148,
    category: 'best-sellers',
    features: ['100% Premium Cotton', 'Elegant Flower Embroidery', 'Soft Stretch Denim Shorts', 'Breathable & Skin-Friendly'],
    variants: ['White / Sky Blue', 'Soft Pink / Denim'],
    sizes: ['0-6 Months', '6-12 Months', '1-2 Years', '2-3 Years', '3-4 Years'],
    stock: 45,
    badge: '-30%'
  },
  {
    id: 'girls-pink-floral',
    name: 'Girls\' Pink Floral Suit',
    price: 2274,
    originalPrice: 3249,
    description: 'Super soft printed floral summer wear suit with elegant design accents for baby girls.',
    longDescription: 'Treat your little princess to this gorgeous Pink Floral Suit. Designed for the dynamic Pakistani summers, it combines lightweight premium lawn-style cotton with a delightful floral pattern print. Comes with a soft t-shirt featuring a cartoon girl illustration and loose-fitting comfortable pajamas with matching floral borders.',
    image: 'https://images.unsplash.com/photo-1519689680058-324335c77ebe?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 96,
    category: 'best-sellers',
    features: ['Extra Cool Summer Cotton Fabric', 'Playful Floral Print Borders', 'Stretchable Waistband', 'Odor-free, Hypoallergenic Dyes'],
    variants: ['Soft Pink', 'Sunny Peach'],
    sizes: ['6-12 Months', '1-2 Years', '2-3 Years', '3-4 Years'],
    stock: 28,
    badge: '-30%'
  },
  {
    id: 'baby-boys-casual-suit',
    name: 'Baby Boys Casual Suit',
    price: 1854,
    originalPrice: 2649,
    description: 'Smart black monogram patterned short-sleeve button-up shirt with premium casual matching shorts.',
    longDescription: 'Make your little gentleman stand out in family gatherings. Crafted in luxury organic cotton with a stylish geometric monochrome monogram print. The short-sleeve collared shirt is super breezy, paired with comfortable matching black pull-on shorts. Perfect for casual evening crawls and parties alike.',
    image: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&q=80&w=600',
    rating: 4.7,
    reviewsCount: 88,
    category: 'best-sellers',
    features: ['100% Breathable Viscose-Cotton', 'Button-down front structure', 'Non-restrictive hip fit', 'Luxurious smooth touch'],
    variants: ['Charcoal Black', 'Classic Navy'],
    sizes: ['0-6 Months', '6-12 Months', '1-2 Years', '2-3 Years'],
    stock: 34,
    badge: '-30%'
  },
  {
    id: 'baby-girls-striped-suit',
    name: 'Baby Girls Striped Suit',
    price: 2274,
    originalPrice: 3249,
    description: 'Beautiful vertical grey striped top with cute frill-sleeve design and matching striped trousers.',
    longDescription: 'A classic design remastered with high comfort. This Baby Girls Striped Suit features a relaxed fit top adorned with frilled shoulder sleeves, round-neck cut, and comfortable matching striped pants. Made with flexible lightweight cotton-linen fabric that handles high playtime activities beautifully.',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 112,
    category: 'best-sellers',
    features: ['Cotton-Linen Breathable Weave', 'Comfort elastic waistband', 'Lovely Flutter Ruffle Sleeves', 'Zero irritation seamless stitching'],
    variants: ['Slate Striped', 'Blush Striped'],
    sizes: ['6-12 Months', '1-2 Years', '2-3 Years', '3-4 Years'],
    stock: 19,
    badge: '-30%'
  },

  // --- NEW ARRIVALS ---
  {
    id: 'baby-boys-blue-tshirt',
    name: 'Baby Boys Blue T-Shirt & Shorts',
    price: 804,
    originalPrice: 1149,
    description: 'Lovely soft blue t-shirt featuring "WILD" text & cute giraffe illustrations, complete with matching black shorts.',
    longDescription: 'Bring joy to your kids playtime routines! This premium set features an adorable high-density color-block t-shirt with screen-printed jungle elements. Paired with versatile dark black pull-up sports shorts. Crafted from double-combed cotton that stands up to infinite machine washing cycles.',
    image: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 65,
    category: 'new-arrivals',
    features: ['100% Combed Organic Cotton', 'Soft-touch water-based printing', 'Elastic waist shorts', 'Highly moisture-wicking'],
    variants: ['Sky Blue', 'Light Yellow'],
    sizes: ['0-6 Months', '6-12 Months', '1-2 Years', '2-3 Years'],
    stock: 40,
    badge: '-30%'
  },
  {
    id: 'baby-boys-teddy-tshirt',
    name: 'Baby Boys Teddy T-Shirt Set',
    price: 999,
    originalPrice: 1429,
    description: 'High-quality block-color cream t-shirt with cute teddy patch pocket details, paired with denim shorts.',
    longDescription: 'Stylish retro vibes for your little boy. This smart outfit features a high-end cream t-shirt accented with vertical corduroy texture details and a cute soft toy bear face peeking from the front pocket. Finished with premium elasticated pocket denim shorts.',
    image: 'https://images.unsplash.com/photo-1519689680058-324335c77ebe?auto=format&fit=crop&q=80&w=600',
    rating: 4.6,
    reviewsCount: 41,
    category: 'new-arrivals',
    features: ['Premium textured soft knit', 'Real embroidery teddy patch', 'Durable wash denim shorts', 'Safe non-metal fittings'],
    variants: ['Beige / Blue Denim', 'Oatmeal / Black Denim'],
    sizes: ['6-12 Months', '1-2 Years', '2-3 Years', '3-4 Years'],
    stock: 25,
    badge: 'Popular'
  },
  {
    id: 'baby-boys-green-tshirt',
    name: 'Baby Boys Green T-Shirt',
    price: 1294,
    originalPrice: 1849,
    description: 'Vibrant lime green summer t-shirt featuring "Surfing Champion" seaside print illustrations.',
    longDescription: 'Let your boy explore the summer heat with supreme confidence. This dynamic green t-shirt is made of ultra-breathable open-end cotton knit. The beachy sunset print is perfectly stylized with eco-secure inks that do not peel or crack.',
    image: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&q=80&w=600',
    rating: 4.7,
    reviewsCount: 38,
    category: 'new-arrivals',
    features: ['100% Ring-spun Cotton', 'Premium beach surfing design', 'Soft rib-knit neckline', 'Cool-tech sweat resistance'],
    variants: ['Lime Green', 'Sunset Orange'],
    sizes: ['1-2 Years', '2-3 Years', '3-4 Years', '4-5 Years'],
    stock: 30,
    badge: '-30%'
  },

  // --- SHORTS & PANTS ---
  {
    id: 'basic-kids-shorts',
    name: 'Basic Kids Cotton Shorts',
    price: 403,
    originalPrice: 575,
    description: 'Super stretchable basic off-white lounge shorts with drawstrings for daily home play.',
    longDescription: 'The absolute daily essential. Made of soft premium cotton fleece, these shorts feature an adjustable drawstring waistband, deep mock pockets, and a generous hip space to easily accommodate diaper changes without tightening.',
    image: 'https://images.unsplash.com/photo-1519689680058-324335c77ebe?auto=format&fit=crop&q=80&w=600',
    rating: 4.5,
    reviewsCount: 224,
    category: 'shorts-pants',
    features: ['Premium Soft Cotton Fleece', 'Adjustable Cotton Drawstrings', 'Diaper-friendly roomy fit', 'Machine washable'],
    variants: ['Off-White', 'Heather Grey', 'Charcoal', 'Navy'],
    sizes: ['0-6 Months', '6-12 Months', '1-2 Years', '2-3 Years'],
    stock: 150,
    badge: '-30%'
  },
  {
    id: 'boys-blue-printed-shorts',
    name: 'Boys Blue Printed Shorts',
    price: 874,
    originalPrice: 1249,
    description: 'Delightful aqua blue shorts adorned with cute printed marine wildlife & dinosaur illustrations.',
    longDescription: 'Make summer splashes playful! This printed cotton shorts features premium little dino and crocodile characters floating in an adorable aqua background. Equipped with a contrast mint green rib-knit waistband and sturdy drawstrings.',
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 79,
    category: 'shorts-pants',
    features: ['Premium Breathable Cotton Poplin', 'Vibrant non-toxic print', 'High stretch ribbed waistband', 'Quick-dry property'],
    variants: ['Aqua Blue Marine', 'Yellow Safari'],
    sizes: ['6-12 Months', '1-2 Years', '2-3 Years', '3-4 Years'],
    stock: 65,
    badge: '-30%'
  },
  {
    id: 'boys-black-denim-pants',
    name: 'Boys Black Denim Pants',
    price: 1224,
    originalPrice: 1749,
    description: 'Stylish premium black washed denim jeans with stretch waistband and front button detailing.',
    longDescription: 'Get real high-street quality for your young boy. Constructed from premium flexible knit denim that stretches in all 4 directions, allowing unlimited crawls, runs, and jumps. Washed beautifully to match casual shirts & t-shirts.',
    image: 'https://images.unsplash.com/photo-1519689680058-324335c77ebe?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 93,
    category: 'shorts-pants',
    features: ['Super Soft Knit Denim', '4-Way stretch technology', 'Washed charcoal finish', 'Adjustable hidden internal waistband elastic'],
    variants: ['Faded Black', 'Jet Black'],
    sizes: ['1-2 Years', '2-3 Years', '3-4 Years', '4-5 Years'],
    stock: 48,
    badge: '-30%'
  },
  {
    id: 'boys-blue-denim-pants',
    name: 'Boys Blue Denim Pants',
    price: 1224,
    originalPrice: 1749,
    description: 'Classic rich blue washed denim jeans featuring soft waistband and convenient elastic cuffs.',
    longDescription: 'The quintessential denim wear. Crafted in authentic premium indigo denim yarn with special pre-softening wash treatments that ensure no stiffness or scratchiness. Features detailed orange stitching, functional pockets, and easy pull-on waist.',
    image: 'https://images.unsplash.com/photo-1519689680058-324335c77ebe?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 104,
    category: 'shorts-pants',
    features: ['Pre-softened premium indigo denim', 'Detailed classic contrast stitch', 'No-pinch soft waistband', 'Functional back pockets'],
    variants: ['Vintage Indigo', 'Light Wash Blue'],
    sizes: ['1-2 Years', '2-3 Years', '3-4 Years', '4-5 Years'],
    stock: 50,
    badge: '-30%'
  },

  // --- NIGHTSUITS ---
  {
    id: 'space-print-night-suit',
    name: 'Space Print Night Suit',
    price: 1199,
    originalPrice: 1713,
    description: 'Comfortable beige cream nightsuit with full sleeves, styled with adorable planets and space rocket prints.',
    longDescription: 'Take your kid on a trip to the dream stars! This long-sleeve nightsuit features premium planetary and rocket patterns across super soft combed interlock cotton. Features comfortable front piping buttons and relaxed pajama bottom with cuffs.',
    image: 'https://images.unsplash.com/photo-1541412031570-3df08e9d4df2?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 119,
    category: 'nightsuits',
    features: ['Heavy Combed Interlock Cotton', 'Cute Galactic Rocket Prints', 'Heat retention cuffs', 'Buttoned collared front'],
    variants: ['Beige Space', 'Blue Starway'],
    sizes: ['6-12 Months', '1-2 Years', '2-3 Years', '3-4 Years'],
    stock: 35,
    badge: 'Best Comfort'
  },
  {
    id: 'bear-print-night-suit',
    name: 'Bear Print Night Suit',
    price: 749,
    originalPrice: 1070,
    description: 'Ultra-sweet pastel pink winter-soft nightsuit with cozy bear prints all over.',
    longDescription: 'Provide extreme comfort during cold nights. Made from premium double-layered soft jersey knit cotton. Embellished with playful cartoon teddy bears, featuring secure chest snaps and highly stretchable ribbed pajamas.',
    image: 'https://images.unsplash.com/photo-1541412031570-3df08e9d4df2?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 82,
    category: 'nightsuits',
    features: ['Double-layer premium cotton jersey', 'Lovely Teddy Bear pattern', 'Snug ribbed wrists & ankles', 'All-season sleep comforting'],
    variants: ['Sweet Pink Bear', 'Mint Green Bear'],
    sizes: ['0-6 Months', '6-12 Months', '1-2 Years', '2-3 Years'],
    stock: 45,
    badge: '-30%'
  },
  {
    id: 'star-print-night-suit',
    name: 'Star Print Night Suit',
    price: 649,
    originalPrice: 927,
    description: 'Lovely white base nightsuit patterned with clean small blue stars and soft contrast navy buttons.',
    longDescription: 'Classic and soothing. This premium white nightsuit is covered with minimalistic midnight blue starry patterns. Features a breathable cool cotton touch, smart shirt collar, and contrast dark blue piping detail lines.',
    image: 'https://images.unsplash.com/photo-1541412031570-3df08e9d4df2?auto=format&fit=crop&q=80&w=600',
    rating: 4.7,
    reviewsCount: 61,
    category: 'nightsuits',
    features: ['Lightweight Breathable Cotton', 'Contrast piping & luxury buttons', 'All-over minimal star print', 'Scratch-free satin brand tag'],
    variants: ['White / Blue Stars', 'Cream / Gold Stars'],
    sizes: ['6-12 Months', '1-2 Years', '2-3 Years', '3-4 Years'],
    stock: 22,
    badge: '-30%'
  },
  {
    id: 'anchor-print-night-suit',
    name: 'Anchor Print Night Suit',
    price: 749,
    originalPrice: 1070,
    description: 'Vibrant anchor red nightsuit with cute nautical motifs and full soft fleece lining.',
    longDescription: 'Nautical-themed luxury for your baby boy or girl. Boasting rich crimson red background covered with cute white naval anchors. Easy chest buttoning, extra-soft waistband, and cozy thermal-insulated weave.',
    image: 'https://images.unsplash.com/photo-1541412031570-3df08e9d4df2?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 54,
    category: 'nightsuits',
    features: ['Thermal-insulated interlock weave', 'Vibrant nautical print', 'Elasticated comfortable trousers', 'Eco-safe skin friendly dye'],
    variants: ['Anchor Red', 'Ocean Navy'],
    sizes: ['0-6 Months', '6-12 Months', '1-2 Years', '2-3 Years'],
    stock: 40,
    badge: '-30%'
  },

  // --- ESSENTIALS & BAGS ---
  {
    id: 'printed-baby-bag-backpack',
    name: 'Printed Baby Bag Backpack',
    price: 1499,
    originalPrice: 2140,
    description: 'Spacious and stylish pastel baby nursery backpack with multiple insulated milk bottle slots and compartments.',
    longDescription: 'The ultimate diaper bag for outdoor strolls. Features beautiful woodland forest animal prints, water-resistant oxford shell, heavy duty zipper pulls, and intelligent thermal-insulated compartments that keep baby milk bottles warm for hours.',
    image: 'https://images.unsplash.com/photo-1595079676339-1534801ad6cf?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 98,
    category: 'essentials',
    features: ['Water-resistant oxford material', 'Insulated warm bottle slots', 'Padded backpack shoulder straps', 'Wide fish-mouth easy opening'],
    variants: ['Forest Sage', 'Nordic Blush'],
    sizes: ['Standard Large'],
    stock: 25,
    badge: 'Best Bag'
  },
  {
    id: 'luxury-baby-girl-suit',
    name: 'Luxury Baby Girl Set',
    price: 1999,
    originalPrice: 2856,
    description: 'Gorgeously styled luxury 4-piece gifting set containing top, pants, bib & matching hat.',
    longDescription: 'An perfect gift for newborn baby showers. Made of luxurious, ultra-soft luxury combed cotton. Decorated with elegant satin bows, frill trims, and coordinating bib and cute cap set.',
    image: 'https://images.unsplash.com/photo-1515488042361-404e9250afef?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 76,
    category: 'essentials',
    features: ['4-Piece comprehensive setup', 'Perfect high-grade gift box', 'Frilled border trim details', 'Anti-allergy metal press snaps'],
    variants: ['Luxury Pink', 'Ivory White'],
    sizes: ['Newborn', '0-3 Months', '3-6 Months'],
    stock: 12,
    badge: 'Premium'
  },
  {
    id: 'stylish-baby-carry-nest',
    name: 'Stylish Baby Carry Nest',
    price: 1799,
    originalPrice: 2570,
    description: 'Soft and secure baby travel carry nest decorated with cute feather prints and zip locks.',
    longDescription: 'Keep your newborn cozy and safe wherever you travel. This carry nest functions as a highly comfortable sleeping pod and wrapping blanket. Designed with breathable cotton shell and safe pillow support to defend head structure.',
    image: 'https://images.unsplash.com/photo-1515488042361-404e9250afef?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 43,
    category: 'essentials',
    features: ['Cozy dual zipper zip opening', 'Head-support pillow molding', '100% Breathable cotton shell', 'Lightweight & portable travel nest'],
    variants: ['Pink Feather', 'Aqua Feather', 'Grey Stars'],
    sizes: ['Newborn - 6 Months'],
    stock: 18,
    badge: 'New'
  },
  {
    id: 'little-gentleman-checked-suit',
    name: 'Little Gentleman Checked Suit',
    price: 2199,
    originalPrice: 3140,
    description: 'Dashing baby boys dress suit with checked vest jacket pattern and white collared shirt details.',
    longDescription: 'The perfect attire for weddings and family events. This premium checked suit features a mock waistcoat vest sewn seamlessly over a soft button-up white shirt, complete with an attached bow tie and coordinating checked trousers. Soft non-scratch fabrics.',
    image: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&q=80&w=600',
    rating: 5.0,
    reviewsCount: 37,
    category: 'essentials',
    features: ['Checked formal vest layout', 'Stitched bowtie and collar', 'Elastic back dress trousers', 'Completely comfortable inner linings'],
    variants: ['Beige Checked', 'Grey Checked'],
    sizes: ['6-12 Months', '1-2 Years', '2-3 Years', '3-4 Years'],
    stock: 15,
    badge: 'Best Seller'
  }
];

export const REVIEWS: Review[] = [
  { id: 'rev-1', writer: 'Abdul Haseeb', rating: 5, date: 'June 18, 2026', text: 'Good Quality' },
  { id: 'rev-2', writer: 'Ayesha', rating: 5, date: 'June 20, 2026', text: 'The fabric is incredibly soft, breathable, and gentle on my baby\'s sensitive skin.' },
  { id: 'rev-3', writer: 'Hassan', rating: 5, date: 'June 23, 2026', text: 'Sweet Baby Clothing has become my go-to website for gifting. I recently bought a newborn gift set for my sister\'s baby shower, and everyone loved it!' }
];

export const BANNER_SLIDES: BannerSlide[] = [
  {
    id: 'slide-1',
    title: 'THE SWEET BABY SHOP',
    subtitle: 'Small in Size, BIG in Style',
    priceText: 'Outfits that bring smiles, comfort & confidence 🧡',
    badge: 'SOFT FABRIC • PREMIUM QUALITY • TRENDY DESIGN',
    tagline: 'FAST DELIVERY • PREMIUM QUALITY • EASY RETURNS',
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=1200',
    linkCategory: 'all'
  },
  {
    id: 'slide-2',
    title: 'New Arrivals Collection',
    subtitle: 'Fresh & Cozy Summer Wear',
    priceText: 'Starting From Rs. 804 Only',
    badge: 'Flat 30% Off',
    tagline: 'Beautiful pastel t-shirts, adorable floral sets and soft linen frocks designed with baby love.',
    image: 'https://images.unsplash.com/photo-1515488042361-404e9250afef?auto=format&fit=crop&q=80&w=1200',
    linkCategory: 'new-arrivals'
  }
];
